update scripts

diff --git a/aliases_mac b/aliases_mac
--- a/aliases_mac
+++ b/aliases_mac
@@ -1,31 +1,27 @@
-alias ls="ls -G"
-alias loge="tail -n 5 -f /opt/local/apache2/logs/error_log | colorize"
-alias loga="tail -n 5 -f /opt/local/apache2/logs/access_log | colorize"
+#alias ls="ls -G"
+alias loge="tail -n 5 -f /private/var/log/apache2/error_log | ccze -A"
+alias loga="tail -n 5 -f /private/var/log/apache2/access_log | ccze -A"
 alias console="open -a Console"
 
-# Services
-alias service-apache="sudo /opt/local/apache2/bin/apachectl restart"
-alias service-memcached="/usr/local/bin/memcached -d"
-alias service-mysql='sudo /opt/local/etc/LaunchDaemons/org.macports.mysql5/mysql5.wrapper restart'
-alias service-rabbitmq='rabbitmq-server'
-alias service-mongodb='mongod'
-alias service-mail='sudo postfix start'
-alias service-redis='redis-server /usr/local/etc/redis.conf'
 
-# Conf files
-alias apache.conf="sudo subl /opt/local/apache2/conf/httpd.conf"
-alias php.ini="sudo subl /opt/local/etc/php5/php.ini"
-alias bash_profile="subl ~/.bash_profile"
+# OLD
+# Customize BASH PS1 prompt to show current GIT repository and branch.
+#export PS1='$(git branch &>/dev/null; if [ $? -eq 0 ]; then \
+#echo "\[\e[0;32m\][GIT: \e[0;31m\]$(basename `pwd`); \e[0;33m\]$(git branch | grep ^*|sed s/\*\ //) \
+#$(echo `git status` | grep "nothing to commit" > /dev/null 2>&1; if [ "$?" -eq "0" ]; then \
+#echo "\e[0;32m\]clean"; else \
+#echo "\e[0;31m\]dirty"; fi)\e[0;32m\]] \$ "; else \
+#echo "\[\e[0;31m\][\w]\[\e[m\] \$ "; fi) \e[0m\]'
 
-#  Customize BASH PS1 prompt to show current GIT repository and branch.
-export PS1='$(git branch &>/dev/null; if [ $? -eq 0 ]; then \
-echo "\[\e[0;32m\][GIT: \e[0;31m\]$(basename `pwd`); \e[0;33m\]$(git branch | grep ^*|sed s/\*\ //) \
-$(echo `git status` | grep "nothing to commit" > /dev/null 2>&1; if [ "$?" -eq "0" ]; then \
-echo "\e[0;32m\]clean"; else \
-echo "\e[0;31m\]dirty"; fi)\e[0;32m\]] \$ "; else \
-echo "\[\e[0;31m\][\w]\[\e[m\] \$ "; fi) \e[0m\]'
-
-
-
+#GIT_PS1_SHOWUPSTREAM="auto"
+#GIT_PS1_SHOWCOLORHINTS="yes"
+#GIT_PS1_SHOWDIRTYSTATE=1
+#source ./scripts/git-prompt.sh
+#export PS1='$(__git_ps1 "(%s)") \W $ '
+# Git branch in prompt.
+#parse_git_branch() {
+#    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
+#}
+#export -n PS1="\W\[\033[32m\]\$(parse_git_branch)\[\033[00m\] $ "
 
 
